#!/bin/bash

CLVR_DIR=~/Common/Sources/Cantilever
CLVR="$CLVR_DIR/cantilever"
CLVR_LIB="$CLVR_DIR/foundation.clvr"
WRAP=

if [ -n "`type -f rlwrap`" ]; then
	WRAP="rlwrap -b '' -f $CLVR_LIB -f . -pPurple"
fi

exec $WRAP $CLVR $CLVR_LIB
