#!/bin/bash

SCR_PATH="`readlink $0`"
CLVR_DIR="`dirname $SCR_PATH`/../"
if [ -z "$CLVR_DIR" ]; then
	echo "You should symlink the cantilever script in Misc"
	echo "into your path"
	exit 1
fi

CLVR="$CLVR_DIR/cantilever"
CLVR_LIB="$CLVR_DIR/foundation.clvr"
WRAP=

if [ -n "`type -f rlwrap`" ]; then
	WRAP="rlwrap -b '' -f $CLVR_LIB -f . -pPurple"
fi

exec $WRAP $CLVR $CLVR_LIB
